name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          run: yarn install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          run: yarn build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          run: yarn test # will run `yarn test` command
